# Fitzgerald Final Project-Tidied Datasets with Raw

# Demographic Race Data for Cuyahoga County 2019

In [1]:
print('hello fitz')

hello fitz

- This dataset came from the US Census Bureau from data.census.gov
- You can download the datasets from [here](https://data.census.gov/cedsci/)
- For the 2019 Cuyahoga County Demogrpahic data related to age, race, sex, gender, population, ethnicity, and more, this is the link to the dataset itself [here](https://data.census.gov/cedsci/table?q=race&g=0500000US39035&tid=ACSDP1Y2019.DP05&hidePreview=true)
- For the [csv file for raw 2019 demographic race data](https://drive.google.com/file/d/1E9ihVnTVJj7IBhhg-XEdBwm3KtRYRpz6/view?usp=sharing) this is the link
- I want to see how the data affected different demographics within the county from the 2019 data and compare it to 2020's data. 

- For the [csv file for tidied 2019 demographic race data](https://drive.google.com/file/d/1a7whC4-pGGTR8spGwYv9FExM1oPw42z1/view?usp=sharing) this is the tidied link
- I took out all other types of demographic data and focused more on the race data with the estimated population and margin for error, plus the populace percentage and percentage margin for error. I included margin for error due to previous difficulty with the tidying and making sure the numbers matched. 
- I was looking at the race breakdown for Cuyahoga in 2019 and also looking at the percentage to help in relating data with PM 2.5 in my other two datasets. Two of the more affected populations of COVID-19, black/african americans as well as latino or hispanic people make up 35.5% of the county population.  
- This will help in seeing how PM 2.5 affects the people located around different areas in Cuyahoga.

In [5]:
import pandas as pd

In [8]:
df = pd.read_csv("2019-cuyahoga-race_raw.csv")
df.head(10)

,Unnamed: 0,"Cuyahoga County, Ohio!!",Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Label,Estimate,Margin of Error,Percent,Percent Margin of Error
1,SEX AND AGE,NaN,NaN,NaN,NaN
2,Total population,"1,235,072",*****,"1,235,072",(X)
3,Male,"589,073",±187,47.70%,±0.1
4,Female,"645,999",±187,52.30%,±0.1
5,Sex ratio (males per 100 females),91.2,±0.1,(X),(X)
6,Under 5 years,"69,888",±149,5.70%,±0.1
7,5 to 9 years,"64,268","±3,120",5.20%,±0.3
8,10 to 14 years,"76,255","±3,129",6.20%,±0.3
9,15 to 19 years,"72,567",±282,5.90%,±0.1

In [9]:
df.tail(10)

,Unnamed: 0,"Cuyahoga County, Ohio!!",Unnamed: 2,Unnamed: 3,Unnamed: 4
85,Native Hawaiian and Other Pacific ...,203,±182,0.00%,±0.1
86,Some other race alone,"3,480","±1,644",0.30%,±0.1
87,Two or more races,"30,456","±4,443",2.50%,±0.4
88,Two races including Some other...,674,±415,0.10%,±0.1
89,Two races excluding Some other...,"29,782","±4,440",2.40%,±0.4
90,Total housing units,"617,202","±1,287",(X),(X)
91,"CITIZEN, VOTING AGE POPULATION",NaN,NaN,NaN,NaN
92,"Citizen, 18 and over population","943,990","±4,577","943,990",(X)
93,Male,"440,583","±2,764",46.70%,±0.1
94,Female,"503,407","±2,338",53.30%,±0.1

In [12]:
df.shape

(95, 5)

In [15]:
df = pd.read_csv("2019-cuyahoga-race_tidied.csv")
df.head(10)

,Race,Estimated Population,Margin of Error,Percent of Populace,% Margin of Error
0,Hispanic or Latino (of any race),"77,343",*****,6.30%,*****
1,White alone,"720,622","±1,569",58.30%,±0.1
2,Black or African American alone,"360,118","±4,211",29.20%,±0.3
3,American Indian and Alaska Native alone,"2,168",±547,0.20%,±0.1
4,Asian alone,"40,682","±1,410",3.30%,±0.1
5,Native Hawaiian and Other Pacific Islander alone,203,±182,0.00%,±0.1
6,Some other race alone,"3,480","±1,644",0.30%,±0.1
7,Two or more races,"30,456","±4,443",2.50%,±0.4
8,Total Estimated Population,"1,235,072",*****,100.00%,*****

In [16]:
df.tail(10)

,Race,Estimated Population,Margin of Error,Percent of Populace,% Margin of Error
0,Hispanic or Latino (of any race),"77,343",*****,6.30%,*****
1,White alone,"720,622","±1,569",58.30%,±0.1
2,Black or African American alone,"360,118","±4,211",29.20%,±0.3
3,American Indian and Alaska Native alone,"2,168",±547,0.20%,±0.1
4,Asian alone,"40,682","±1,410",3.30%,±0.1
5,Native Hawaiian and Other Pacific Islander alone,203,±182,0.00%,±0.1
6,Some other race alone,"3,480","±1,644",0.30%,±0.1
7,Two or more races,"30,456","±4,443",2.50%,±0.4
8,Total Estimated Population,"1,235,072",*****,100.00%,*****

In [17]:
df.shape

(9, 5)

# 2019 EPA PM 2.5 Data

- This is a dataset came from epa.gov 
- You can [download this epa dataset from here](https://www.epa.gov/outdoor-air-quality-data/download-daily-data)
- This dataset is showing Particulate Matter 2.5 (PM 2.5) from 2019 for Cuyahoga County
- [Here](https://drive.google.com/file/d/1E9ihVnTVJj7IBhhg-XEdBwm3KtRYRpz6/view?usp=sharing) is the link to that dataset csv file for 2019
- I want to figure out how the particulate matter 2.5 changed from before COVID and apply it to the race breakdown for the county to help show who was affected the most and the least. This is going to be used as a comparison to the 2020 data. 

- For the [csv file for tidied 2019 epa pm 2.5 data](https://drive.google.com/file/d/1a7whC4-pGGTR8spGwYv9FExM1oPw42z1/view?usp=sharing) this is the tidied link
- I took out all uneccessary data and focused on the dates collected, the daily mean change of PM 2.5 by it's unit of ug/m3, and looking at AQI for each site it was measured at. 
- AQI is the indcicator where the higher the number, the less satisfactory the air quality which you can find [more of a description from here](https://www.airnow.gov/aqi/aqi-basics/)
- This data will be one chart or graph or combined with 2020 data if neccessary to show the difference in the air quality, as AQI rises when the daily mean change of PM 2.5 rose as well.

In [18]:
df = pd.read_csv("2019-pm-cuyahoga_raw.csv")
df.head(10)

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/03/2019,AQS,390350034,1,6.4,ug/m3 LC,27,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
1,01/06/2019,AQS,390350034,1,3.0,ug/m3 LC,13,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
2,01/09/2019,AQS,390350034,1,3.2,ug/m3 LC,13,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
3,01/12/2019,AQS,390350034,1,5.9,ug/m3 LC,25,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
4,01/15/2019,AQS,390350034,1,20.3,ug/m3 LC,68,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
5,01/18/2019,AQS,390350034,1,16.4,ug/m3 LC,60,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
6,01/21/2019,AQS,390350034,1,3.7,ug/m3 LC,15,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
7,01/24/2019,AQS,390350034,1,5.7,ug/m3 LC,24,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
8,01/27/2019,AQS,390350034,1,9.4,ug/m3 LC,39,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
9,02/01/2019,AQS,390350034,1,10.6,ug/m3 LC,44,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256

In [19]:
df.tail(10)

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
1874,12/05/2019,AQS,390351002,1,4.9,ug/m3 LC,20,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1875,12/06/2019,AQS,390351002,1,4.9,ug/m3 LC,20,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1876,12/08/2019,AQS,390351002,1,7.6,ug/m3 LC,32,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1877,12/11/2019,AQS,390351002,1,6.8,ug/m3 LC,28,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1878,12/14/2019,AQS,390351002,1,18.5,ug/m3 LC,64,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1879,12/17/2019,AQS,390351002,1,9.4,ug/m3 LC,39,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1880,12/20/2019,AQS,390351002,1,18.4,ug/m3 LC,64,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1881,12/23/2019,AQS,390351002,1,8.0,ug/m3 LC,33,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1882,12/26/2019,AQS,390351002,1,4.5,ug/m3 LC,19,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1883,12/29/2019,AQS,390351002,1,8.1,ug/m3 LC,34,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667

In [20]:
df.shape

(1884, 20)

In [22]:
df = pd.read_csv("2019-pm-cuyahoga_tidied.csv")
df.head(10)

,Date,Daily Mean PM2.5 Concentration (ug/m3 LC),Daily AQI Value,County Site Name
0,01/03/2019,6.4,27,District 6
1,01/06/2019,3.0,13,District 6
2,01/09/2019,3.2,13,District 6
3,01/12/2019,5.9,25,District 6
4,01/15/2019,20.3,68,District 6
5,01/18/2019,16.4,60,District 6
6,01/21/2019,3.7,15,District 6
7,01/24/2019,5.7,24,District 6
8,01/27/2019,9.4,39,District 6
9,02/01/2019,10.6,44,District 6

In [23]:
df.tail(10)

,Date,Daily Mean PM2.5 Concentration (ug/m3 LC),Daily AQI Value,County Site Name
1874,12/05/2019,4.9,20,Brookpark
1875,12/06/2019,4.9,20,Brookpark
1876,12/08/2019,7.6,32,Brookpark
1877,12/11/2019,6.8,28,Brookpark
1878,12/14/2019,18.5,64,Brookpark
1879,12/17/2019,9.4,39,Brookpark
1880,12/20/2019,18.4,64,Brookpark
1881,12/23/2019,8.0,33,Brookpark
1882,12/26/2019,4.5,19,Brookpark
1883,12/29/2019,8.1,34,Brookpark

In [24]:
df.shape

(1884, 4)

- This is a dataset came from epa.gov 
- You can [download this epa dataset from here](https://www.epa.gov/outdoor-air-quality-data/download-daily-data)
- This dataset is showing Particulate Matter 2.5 (PM 2.5) from 2020 for Cuyahoga County
- [Here](https://drive.google.com/file/d/1X6_8RyYL4hc2fkTZaGuNYOfOLEEd6T35/view?usp=sharing) is the link to that dataset csv file for 2019
- I want to figure out how the particulate matter 2.5 changed from before COVID and apply it to the race breakdown for the county to help show who was affected the most and the least. 

- For the [csv file for tidied 2020 epa pm 2.5 data](https://drive.google.com/file/d/1iTCMiPrvWgVV07wthCDyUqmxCNeitRD7/view?usp=sharing) this is the tidied link
- I took out all uneccessary data and focused on the dates collected, the daily mean change of PM 2.5 by it's unit of ug/m3, and looking at AQI for each site it was measured at. 
- AQI is the indcicator where the higher the number, the less satisfactory the air quality which you can find [more of a description from here](https://www.airnow.gov/aqi/aqi-basics/)
- I was able to look at this data and the 2020 and see around the time that COVID hit, each site's numbers dipped, which was a good thing compared to 2019's numbers. Now it's a matter of seeing how it affected those by the data from race. 
- This data will be one chart or graph or combined with 2019 data if neccessary to show the difference in the air quality, as AQI rises and falls when the daily mean change of PM 2.5 rose and fell as well.

In [25]:
df = pd.read_csv("2020-pm-cuyahoga_raw.csv")
df.head(10)

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,01/01/2020,AQS,390350034,1,6.5,ug/m3 LC,27,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
1,01/04/2020,AQS,390350034,1,6.7,ug/m3 LC,28,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
2,01/07/2020,AQS,390350034,1,6.2,ug/m3 LC,26,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
3,01/10/2020,AQS,390350034,1,4.4,ug/m3 LC,18,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
4,01/13/2020,AQS,390350034,1,5.7,ug/m3 LC,24,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
5,01/16/2020,AQS,390350034,1,6.2,ug/m3 LC,26,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
6,01/19/2020,AQS,390350034,1,10.7,ug/m3 LC,45,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
7,01/22/2020,AQS,390350034,1,13.9,ug/m3 LC,55,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
8,01/25/2020,AQS,390350034,1,4.4,ug/m3 LC,18,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256
9,01/28/2020,AQS,390350034,1,6.4,ug/m3 LC,27,District 6,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.55523,-81.575256

In [26]:
df.tail(10)

,Date,Source,Site ID,POC,Daily Mean PM2.5 Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
1529,09/21/2020,AQS,390351002,1,5.0,ug/m3 LC,21,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1530,09/24/2020,AQS,390351002,1,12.3,ug/m3 LC,51,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1531,09/27/2020,AQS,390351002,1,6.1,ug/m3 LC,25,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1532,09/30/2020,AQS,390351002,1,2.7,ug/m3 LC,11,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1533,10/03/2020,AQS,390351002,1,4.4,ug/m3 LC,18,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1534,10/06/2020,AQS,390351002,1,4.3,ug/m3 LC,18,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1535,10/09/2020,AQS,390351002,1,5.7,ug/m3 LC,24,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1536,10/12/2020,AQS,390351002,1,4.0,ug/m3 LC,17,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1537,10/15/2020,AQS,390351002,1,2.6,ug/m3 LC,11,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667
1538,10/18/2020,AQS,390351002,1,4.8,ug/m3 LC,20,Brookpark,1,100.0,88101,PM2.5 - Local Conditions,17460,"Cleveland-Elyria, OH",39,Ohio,35,Cuyahoga,41.39629,-81.818667

In [27]:
df.shape

(1539, 20)

In [28]:
df = pd.read_csv("2020-pm-cuyahoga_tidied.csv")
df.head(10)

,Date,Daily Mean PM2.5 Concentration (ug/m3 LC),Daily AQI Value,County Site Name
0,01/01/2020,6.5,27,District 6
1,01/04/2020,6.7,28,District 6
2,01/07/2020,6.2,26,District 6
3,01/10/2020,4.4,18,District 6
4,01/13/2020,5.7,24,District 6
5,01/16/2020,6.2,26,District 6
6,01/19/2020,10.7,45,District 6
7,01/22/2020,13.9,55,District 6
8,01/25/2020,4.4,18,District 6
9,01/28/2020,6.4,27,District 6

In [29]:
df.tail(10)

,Date,Daily Mean PM2.5 Concentration (ug/m3 LC),Daily AQI Value,County Site Name
1529,09/21/2020,5.0,21,Brookpark
1530,09/24/2020,12.3,51,Brookpark
1531,09/27/2020,6.1,25,Brookpark
1532,09/30/2020,2.7,11,Brookpark
1533,10/03/2020,4.4,18,Brookpark
1534,10/06/2020,4.3,18,Brookpark
1535,10/09/2020,5.7,24,Brookpark
1536,10/12/2020,4.0,17,Brookpark
1537,10/15/2020,2.6,11,Brookpark
1538,10/18/2020,4.8,20,Brookpark

In [30]:
df.shape

(1539, 4)